annotationkey_value:
  assay: Assay
  diagnosis: Diagnosis
  tumorType: Tumor Type
  name_project: Center
  studyName: Study
  resourceType: Resource Type
  
annotationkey_display:
  Assay: assay
  Diagnosis: diagnosis
  Tumor Type: tumorType
  Study: studyName
  Resource Type: resourceType

annotationkey_display2:
  Assay: assay
  Diagnosis: diagnosis
  Tumor Type: tumorType
  Study: name_project
  Resource Type : resourceType

sampletype_value:
  individualID: Individuals
  specimenID: Specimens

sampletype_display:
  Individuals: individualID
  Specimens: specimenID
